### ISSUE TITLE
Some symbols could not be displayed

### ISSUE THREAD

**Issue by WordlessEcho** [WordlessEcho/Noto-CJK-VF-Magisk#5]
See: adobe-fonts/source-han-sans#296 and simonsmh/notocjk#25

**Comment by RodertHaung** [comment]
在新版本2.004R中已修復

**Comment by WordlessEcho** [comment]
I am busy recently. Modules will get updates SOON! : )

**Comment by WordlessEcho** [comment]
Fixed e510775
