### ISSUE TITLE
QQ天气小程序界面部分字体Fallback到Noto Serif

### ISSUE THREAD

**Issue by gb0k** [WordlessEcho/Noto-CJK-VF-Magisk#6]
机型是一加7Pro，新添加的fonts_base.xml配置起作用了，所以可以将描述文件中的untested去除。
QQ天气里的地名、温度等字体变成了宋体。如下图
![Screenshot_20210413-202321](https://user-images.githubusercontent.com/30920372/114552132-d6efcf80-9c96-11eb-9b0e-81aaa8efa900.jpg)
同样情况在淘宝收集淘金币界面也有发生，如下图
![Screenshot_20210413-202411~2](https://user-images.githubusercontent.com/30920372/114552300-09013180-9c97-11eb-812c-69436fa6d932.jpg)

用最新notocjk模块的话这些字体都是正常的无衬线字体…
如下图QQ天气界面
![Screenshot_20210413-201940](https://user-images.githubusercontent.com/30920372/114552518-449bfb80-9c97-11eb-9dcc-51b8adba45f8.jpg)

**Comment by WordlessEcho** [comment]
关于这个问题，是和 #2 里一样的。某些浏览器并不直接调用系统的字体，感谢反馈
notocjk做了workaround，所以目前推荐您使用 https://github.com/simonsmh/notocjk

**Comment by gb0k** [comment]
> 关于这个问题，是和 #2 里一样的。某些浏览器并不直接调用系统的字体，感谢反馈
> notocjk做了workaround，所以目前推荐您使用 https://github.com/simonsmh/notocjk

👌好的，谢谢解答，这个issue我就关闭啦。
