### ISSUE TITLE
英文粗体在 MIUI Android 12 上无法显示

### ISSUE THREAD

**Issue by ClowRead1224** [WordlessEcho/Noto-CJK-VF-Magisk#8]
![photo_2021-12-24_09-35-47](https://user-images.githubusercontent.com/96602679/147305163-e8330812-09a2-4f5a-882c-15184cf37efb.jpg)
![photo_2021-12-24_09-35-40](https://user-images.githubusercontent.com/96602679/147305161-ef9a9e08-1002-41a5-9232-3eefb2a330f8.jpg)

**Comment by WordlessEcho** [comment]
你的第一张截图里并没有使用粗体啊？

**Comment by ClowRead1224** [comment]
> 你的第一张截图里并没有使用粗体啊？

是第二张截图使用的粗体，第一张中的 ABCD 字母 没有显示。

**Comment by WordlessEcho** [comment]
我还是不太理解你的意思。是输入一段英文后，再把字族调到粗体没有相应的显示效果这样吗？

**Comment by ClowRead1224** [comment]
> 我还是不太理解你的意思。是输入一段英文后，再把字族调到粗体没有相应的显示效果这样吗？

具体的表现是就刷了模块后系统全局的粗体英文都是显示不出来的，但是常规字重的英文没有问题。我之前是使用 MIUI Android 11 和该模块的 1.7 版本，没有问题。还没有在 Android 11 上试过 2.0 版本。

**Comment by WordlessEcho** [comment]
那麻烦你把 `/system/etc/fonts.xml` 发一下

**Comment by ClowRead1224** [comment]
[fonts.xml.zip](https://github.com/WordlessEcho/Noto-CJK-VF-Magisk/files/7777197/fonts.xml.zip)
已提供

**Comment by WordlessEcho** [comment]
根据你发出的fonts.xml来看，模块似乎没有生效
```xml
<family lang="zh-Hans">
    <font weight="400" style="normal" index="2" postScriptName="NotoSansCJKjp-Regular">
        NotoSansCJK-Regular.ttc
    </font>
    <font weight="400" style="normal" index="2" fallbackFor="serif"
          postScriptName="NotoSerifCJKjp-Regular">NotoSerifCJK-Regular.ttc
    </font>
</family>
<family lang="zh-Hant,zh-Bopo">
    <font weight="400" style="normal" index="3" postScriptName="NotoSansCJKjp-Regular">
        NotoSansCJK-Regular.ttc
    </font>
    <font weight="400" style="normal" index="3" fallbackFor="serif"
          postScriptName="NotoSerifCJKjp-Regular">NotoSerifCJK-Regular.ttc
    </font>
</family>
<family lang="ja">
    <font weight="400" style="normal" index="0" postScriptName="NotoSansCJKjp-Regular">
        NotoSansCJK-Regular.ttc
    </font>
    <font weight="400" style="normal" index="0" fallbackFor="serif"
          postScriptName="NotoSerifCJKjp-Regular">NotoSerifCJK-Regular.ttc
    </font>
</family>
<family lang="ko">
    <font weight="400" style="normal" index="1" postScriptName="NotoSansCJKjp-Regular">
        NotoSansCJK-Regular.ttc
    </font>
    <font weight="400" style="normal" index="1" fallbackFor="serif"
          postScriptName="NotoSerifCJKjp-Regular">NotoSerifCJK-Regular.ttc
    </font>
</family>
```

**Comment by ClowRead1224** [comment]
抱歉，之前上传的是源 font 文件，这份是开启模块的 font 文件。
[fonts.zip](https://github.com/WordlessEcho/Noto-CJK-VF-Magisk/files/7779045/fonts.zip)

**Comment by WordlessEcho** [comment]
嗯……我从`fonts.xml`来看，没有看出有什么问题
能麻烦你再提供一些无法显示粗体英文的截图吗？

**Comment by ClowRead1224** [comment]
![photo_2021-12-27_16-20-25](https://user-images.githubusercontent.com/96602679/147451145-bfd9f533-9952-4155-98f8-9815ae0c8702.jpg)

![photo_2021-12-27_16-20-22](https://user-images.githubusercontent.com/96602679/147451109-6389f433-adde-4bca-929a-4dc0a9cf1c4c.jpg)

**Comment by ClowRead1224** [comment]
上面使用 Magsik 的模块界面作为对比，开启模块后粗体的英文都无法显示出来，包括状态栏的粗体英文也无法显示。

**Comment by WordlessEcho** [comment]
请问你有尝试过[simonsmh/notocjk](https://github.com/simonsmh/notocjk)吗？会不会有同样的问题？

**Comment by ClowRead1224** [comment]
> 请问你有尝试过[simonsmh/notocjk](https://github.com/simonsmh/notocjk)吗？会不会有同样的问题？

也尝试过，同样有此问题。

**Comment by WordlessEcho** [comment]
没什么头绪，因为这个模块只修改中文相关的配置，不应该影响英文

**Comment by simonsmh** [comment]
有可能是因为其他模块冲突了呢，我这边复现不了

**Comment by ClowRead1224** [comment]
我单独安装了一个只有 Google Sans 的模块，发现粗体也无法显示，我猜测可能是 MIUI 的问题吧。不过在网上似乎没有看到和我相同的案例……现在也不能确定。

**Comment by WordlessEcho** [comment]
> 我单独安装了一个只有 Google Sans 的模块，发现粗体也无法显示，我猜测可能是 MIUI 的问题吧。不过在网上似乎没有看到和我相同的案例……现在也不能确定。

如果你还愿意测试的话，我建议你删掉所有模块，单独安装这一个模块看正常还是不正常。正常的话再一个一个地安装并重启以前有的模块试试。不再测试的话，我就把这个issue关掉了。
